Update syncWithSVN.yml

diff --git a/.github/workflows/syncWithSVN.yml b/.github/workflows/syncWithSVN.yml
--- a/.github/workflows/syncWithSVN.yml
+++ b/.github/workflows/syncWithSVN.yml
@@ -36,27 +36,31 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: JADE-SVN-TILAB
-          path: jade_svn_tilab
-          
+          path: jade_svn_tilab     
+
       - name: Install SVN
         run: |
           apt-get update
-          sudo apt-get install -y subversion
-      
-      - name: Install Git and git-svn
-        run: |
-            apt-get update 
-            sudo apt-get install -y git-svn
-
-
-      - name: Check if SVN is installed
-        run: |
+          apt-get install -y subversion
           if ! command -v svn &> /dev/null
           then
-              echo "SVN is not installed"
+              echo "SVN installation failed"
+              exit 1
           else
               svn --version
           fi
+
+      - name: Install Git and git-svn
+        run: |
+            apt-get update 
+            apt-get install -y git-svn
+            if ! command -v git-svn &> /dev/null
+            then
+                echo "git-svn installation failed"
+                exit 1
+            else
+                git-svn --version
+            fi
             
       - name: Checkout SVN repository
         env:
